{
 "title": "Compare Friendli & VLLM",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput (requests/sec)",
   "type": "timeseries",
   "description": "lambda of the Poisson distribution",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(total_responses[10s])", "legendFormat": "{{instance}}" },
    {
     "expr": "experiment_info{instance=\"friendli-exp-exposer:8801\"}",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Current Request Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "experiment_info{instance=\"friendli-exp-exposer:8801\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Input Tokens/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(total_input_tokens[10s])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Throughput (Output Tokens/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(total_output_tokens[10s])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "request_latencies_sum/request_latencies_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Token Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "token_latencies_sum/token_latencies_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TTFT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "time_to_first_tokens_sum/time_to_first_tokens_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TPOT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "time_per_output_tokens_sum/time_per_output_tokens_count",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}