{
 "title": "Single Engine Performance Test",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Request Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "experiment_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Throughput (requests/sec)",
   "type": "timeseries",
   "description": "lambda of the Poisson distribution",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(total_responses[10s])", "legendFormat": "Requests/sec" },
    { "expr": "experiment_info", "legendFormat": "Request Rate" }
   ]
  },
  {
   "title": "Throughput (Input/Output Tokens/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(total_input_tokens[10s])", "legendFormat": "Input Tokens/sec" },
    { "expr": "rate(total_output_tokens[10s])", "legendFormat": "Output Tokens/sec" }
   ]
  },
  {
   "title": "Average TTFT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time_to_first_tokens_sum{mode=\"\"}/time_to_first_tokens_count{mode=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average TPOT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time_per_output_tokens_sum{mode=\"\"}/time_per_output_tokens_count{mode=\"\"}",
     "legendFormat": "Average TPOT"
    }
   ]
  },
  {
   "title": "Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "request_latencies{mode=\"\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "request_latencies_sum{mode=\"\"}/request_latencies_count{mode=\"\"}",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Token Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "token_latencies", "legendFormat": "{{quantile}}" },
    {
     "expr": "token_latencies_sum/token_latencies_count",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "TTFT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "time_to_first_tokens", "legendFormat": "{{quantile}}" },
    {
     "expr": "time_to_first_tokens_sum/time_to_first_tokens_count",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "TPOT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "time_per_output_tokens{mode=\"\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "time_per_output_tokens_sum/time_per_output_tokens_count",
     "legendFormat": "mean"
    }
   ]
  }
 ]
}